version: '3.8'

services:
  spoofer4you:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - JWT_SECRET=your-secure-jwt-secret-change-this
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    restart: unless-stopped